apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    type: postgres-service
    app: demo-voting-app
spec:
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    type: postgres-pod
    app: demo-voting-app
