apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    type: voting-app-service
    app: demo-voting-app
spec:
 type: LoadBalancer
 ports:
   - targetPort: 80
     port: 80
 selector:
   type: voting-app-pod
   app: demo-voting-app